name: PR Events Notification to Slack

on:
  pull_request:
    types: [opened, closed, synchronize]  # Listen to PR open, close, and sync events
  pull_request_review:
    types: [submitted]  # Listen for PR reviews (approved or changes requested)
  status:
    types: [completed]  # Listen for status check completion (pass or fail)

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "channel": "#github",
            "text": "*Pull Request Action Detected*",
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Event:* ${{ github.event_name }}\n*PR Status:* ${{ github.event.pull_request.state }}\n*PR Author:* ${{ github.event.pull_request.user.login }}"
                }
              },
              {
                "type": "section",
                "block_id": "review-section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Review Action:* ${{ github.event.review.state }}\n*Reviewer:* ${{ github.actor }}"
                }
              },
              {
                "type": "section",
                "block_id": "check-status",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Check Status:* ${{ github.event.status.state }}\n*Check Name:* ${{ github.event.status.context }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
