name: Track Repo Actions and Notify Slack

on:
  push:
    branches:
      - main  # Adjust the branch filter as needed
  pull_request:
    types: [opened, closed, synchronize, reopened]  # Adjust event types as needed
  issue_comment:
    types: [created, edited, deleted]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "channel": "#github",
            "text": "*Action in Repo*",
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Repository Action Detected*\n\n*Event:* ${{ github.event_name }}\n*Action by:* ${{ github.actor }}\n*Branch:* ${{ github.ref }}\n*Commit:* ${{ github.sha }}\n*Action Details:* ${{ github.event.head_commit.message }}"
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://www.example.com/logo.png",
                  "alt_text": "repo-logo"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # The webhook URL stored as a GitHub secret
